### ISSUE TITLE
ReadMe improvements

### ISSUE THREAD

**Issue by thorade** [tshort/openmodelica-javascript#2]
I am trying to follow the (very good) ReadMe and here is how far I got and what I noticed:
- Out  of the "several examples" linked from the Readme only the Chua example works, the others are just not present in the mpad repository (but mpad still shows an empty page). The two examples from your fields are working.
- On Xubuntu 16.04 `sudo apt-get install emscripten` did not work for me, I had to install emscripten [as described on the emscripten home page](http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html) (took a couple of hours). The command `emcc -v` does not generate any warnings anymore and the [hello_world.cpp example](http://kripken.github.io/emscripten-site/docs/building_from_source/verify_emscripten_environment.html#verifying-the-emscripten-environment) delivered with emscripten now seems to work. Should I do more testing?
- Is the build directory of OpenModelica really at `/build/lib/omc/emcc/` (starting at top level) or is that path somehow incomplete?
- I have the latest OpenModelica nightly installed. Is re-compiling the Modelica libraries optional or mandatory? Where is the "OpenModelica source location"? Does `apt-get` install the source somewhere on my computer, along with the binaries, or should I clone the OpenModelica/OMCompiler repository? When running the `make` command in the cloned repo, it tells me there is nothing to do, but there already is a file named `pre.js`.

**Comment by thorade** [comment]
Here is where I am stuck: Running `omc PID_Controller.mos` with content as copied from the ReadMe, but adapted path, will generate a lot of files, including the md and xml file. The only generated js file is named `PID_Controller_node.js` instead of `PID_Controller.js` and has a size of only ~650kB. 
Is my emscripten still not working properly? Did I miss anything else? Any help appreciated.

I also asked the same question in the OpenModelica forum:
https://openmodelica.org/forum/default-topic/1939-compile-to-javascript

**Edit:** 
Not sure whether it is relevant, but when searching for OpenModelica with Synaptic, there were some packages available, that were not installed. I installed all of them now, including all dependencies.

One obvious thing I missed: 
One of the generated files is a log file! It tells me that there was no make rule to generate the `PID_Controller.o` file. 

When changing the [`simCodeTarget`](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omchelptext.html#omcflag-simcodetarget) to `C` some .o files are generated, and the log has no errors. When changig the `simCodeTarget` back to `JavaScript` the log complains that the `PID_Controller.o` file is not valid LLVM bitcode.

When changing the `simCodeTarget` to `Cpp`, the log file mentions a couple of undefined references to boost. When changing back to `JavaScript` the log message is again that there was no rule to generate the `PID_Controller.o` file.

Another generated file is the makefile, it mentions the directory `/usr/lib/x86_64-linux-gnu/omc/emcc/` and I assume this is the build directory (instead of `/build/lib/omc/emcc/`). So I copied the .so files and the pre.js file there, but did not notice any effect so far. Or is manually copying stuff to `/usr/...` considered harmful?

**Comment by thorade** [comment]
Closing for now, as I do not know what the current status is in OpenModelica.

**Comment by jmpt97** [comment]
Hi, @thorade where you able to solve this? Or is there any alternatives?

**Comment by thorade** [comment]
Sorry, no. You could try and ask for help in the OpenModelica forum.
